#!/bin/sh

# (wont parse arguments for ssh, wont show warning)
# IT IS EXPECTED ARGUMENTS TO NOT EXECUTE ANY COMMANDS IN THE SSH SESSION, -> AND DROP TO CONNECTED SSH SHELL.

dir_nprefix="${XDG_CACHE_HOME:-$HOME/.cache}"/clipboard-over-ssh/ssh-conected--

for i in "$dir_nprefix"*; do
	parent_ssh_pid=${i#"$dir_nprefix"}
	if [ -d "proc/$parent_ssh_pid" ] || ps -h -o 'pid' -p "$parent_ssh_pid" 1>/dev/null; then
		printf %s\\n "$i"
	else
		rm -v "$i" # yes, verbose. those files should not exists without pid
	fi
done | {
	args_file=$dir_nprefix$(fzf) || exit

	set --
	IFS=''
	while read -r i; do set -- "$@" "$i"; done < "$args_file"
	# dont use var `dir_nprefix` remote path might have different XDG_CACHE_HOME
	ssh "$@" -- 'cat "${XDG_CACHE_HOME:-$HOME/.cache}"/clipboard-over-ssh/ssh-clipboard--"${SSH_CLIENT%%" "*}"'
}
